# Generated by Django 5.0.2 on 2024-04-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
    ]
