# Generated by Django 5.0.2 on 2024-04-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBA_Team',
            fields=[
                ('team_number', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NFL_Team',
            fields=[
                ('team_number', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NHL_Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Valorant_Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NBA_Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('player_points', models.CharField(max_length=10)),
                ('player_rebounds', models.CharField(max_length=10)),
                ('player_shots', models.CharField(max_length=10)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_stats.nba_team')),
            ],
        ),
        migrations.CreateModel(
            name='NFL_Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('passing_yards', models.CharField(max_length=10)),
                ('passing_average_yards', models.CharField(max_length=10)),
                ('passing_attempts', models.CharField(max_length=10)),
                ('passing_completions', models.CharField(max_length=10)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_stats.nba_team')),
            ],
        ),
        migrations.CreateModel(
            name='NHL_Skaters',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.CharField(max_length=10)),
                ('goals', models.CharField(max_length=10)),
                ('assists', models.CharField(max_length=10)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_stats.nhl_team')),
            ],
        ),
        migrations.CreateModel(
            name='NHL_Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_stats.nhl_team')),
            ],
        ),
        migrations.CreateModel(
            name='NHL_Goalies',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('gaa', models.CharField(max_length=10)),
                ('SV_Percent', models.CharField(max_length=10)),
                ('shutouts', models.CharField(max_length=10)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_stats.nhl_team')),
            ],
        ),
        migrations.CreateModel(
            name='Valorant_Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('kills', models.CharField(max_length=10)),
                ('deaths', models.CharField(max_length=10)),
                ('kd', models.CharField(max_length=10)),
                ('ACS', models.CharField(max_length=10)),
                ('Kills_per_round', models.CharField(max_length=10)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_stats.valorant_team')),
            ],
        ),
    ]
