# Generated by Django 5.0.2 on 2024-05-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_stats', '0005_alter_valorant_players_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorant_players',
            options={'managed': False},
        ),
    ]
